package gestionpharmavente;

/**
 * Fenêtre d'accueil de l'application.
 * Permet de naviguer vers les différents écrans (produits, approvisionnements, historique, à propos).
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        btnProduits = new javax.swing.JButton();
        btnAppro = new javax.swing.JButton();
        btnHistorique = new javax.swing.JButton();
        btnApropos = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        btnAppro1 = new javax.swing.JButton();
        btnAppro2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestionPharmaVente - Accueil");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTitre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("GESTION PHARMA");

        btnProduits.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnProduits.setText("Gestion des produits");
        btnProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduitsActionPerformed(evt);
            }
        });

        btnAppro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnAppro.setText("Vente et Facturation");
        btnAppro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApproMouseClicked(evt);
            }
        });
        btnAppro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproActionPerformed(evt);
            }
        });

        btnHistorique.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnHistorique.setText("Historique approvisionnements");
        btnHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriqueActionPerformed(evt);
            }
        });

        btnApropos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnApropos.setText("À propos");
        btnApropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAproposActionPerformed(evt);
            }
        });

        btnQuitter.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnAppro1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnAppro1.setText("Approvisionnement");
        btnAppro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppro1MouseClicked(evt);
            }
        });
        btnAppro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppro1ActionPerformed(evt);
            }
        });

        btnAppro2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnAppro2.setText("Historique Vente");
        btnAppro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppro2MouseClicked(evt);
            }
        });
        btnAppro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApropos, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAppro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAppro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProduits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addComponent(btnAppro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProduits, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAppro1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAppro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAppro2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnApropos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduitsActionPerformed
        new ProduitFramee().setVisible(true);
    }//GEN-LAST:event_btnProduitsActionPerformed

    private void btnApproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproActionPerformed
        
    }//GEN-LAST:event_btnApproActionPerformed

    private void btnHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriqueActionPerformed
        new HistoriqueApproFramee().setVisible(true);
    }//GEN-LAST:event_btnHistoriqueActionPerformed

    private void btnAproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAproposActionPerformed
        new AproposFrameE().setVisible(true);
    }//GEN-LAST:event_btnAproposActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnAppro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppro1ActionPerformed

    private void btnApproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApproMouseClicked
        // TODO add your handling code here:
        new VenteFrame().setVisible(true);
    }//GEN-LAST:event_btnApproMouseClicked

    private void btnAppro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppro2MouseClicked
        // TODO add your handling code here:
        new HistoriqueVenteFrame().setVisible(true);
    }//GEN-LAST:event_btnAppro2MouseClicked

    private void btnAppro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppro2ActionPerformed

    private void btnAppro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppro1MouseClicked
        // TODO add your handling code here:
        new ApprovisionnementFramee().setVisible(true);
    }//GEN-LAST:event_btnAppro1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppro;
    private javax.swing.JButton btnAppro1;
    private javax.swing.JButton btnAppro2;
    private javax.swing.JButton btnApropos;
    private javax.swing.JButton btnHistorique;
    private javax.swing.JButton btnProduits;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JLabel jLabelTitre;
    // End of variables declaration//GEN-END:variables
}
