/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionpharmavente;


import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEM'S KABE FILM
 */
public class HistoriqueVenteFrame extends javax.swing.JFrame {

    /**
     * Historique des ventes (analogue à l'historique des approvisionnements).
     */
    private final VenteDAO venteDAO = new VenteDAO();
    private final LigneVenteDAO ligneVenteDAO = new LigneVenteDAO();
    private final ProduitDAO produitDAO = new ProduitDAO();
    public HistoriqueVenteFrame() {
        initComponents();
        setLocationRelativeTo(null);
        chargerVentes();
    }

    private void chargerVentes() {
        try {
            List<Vente> list = venteDAO.listerTous();
            DefaultTableModel model = (DefaultTableModel) tableAppro.getModel();
            model.setRowCount(0);
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
            for (Vente v : list) {
                Date d = v.getDateVente();
                model.addRow(new Object[]{
                    v.getId(),
                    sdf.format(d),
                    v.getRef()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement des ventes : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppro = new javax.swing.JTable();
        btnRafraichir = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnSupprimerAppro = new javax.swing.JButton();
        btnFac2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historique des approvisionnements");

        tableAppro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE VENTE", "REFERENCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAppro);

        btnRafraichir.setText("Rafraîchir");
        btnRafraichir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRafraichirMouseClicked(evt);
            }
        });

        btnDetails.setText("Détails");
        btnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailsMouseClicked(evt);
            }
        });

        btnSupprimerAppro.setText("Supprimer");
        btnSupprimerAppro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerApproMouseClicked(evt);
            }
        });

        btnFac2.setText("Voir Facture");
        btnFac2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFac2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnRafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSupprimerAppro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnFac2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerAppro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFac2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRafraichirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRafraichirMouseClicked
        chargerVentes();
    }//GEN-LAST:event_btnRafraichirMouseClicked

    private void btnSupprimerApproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerApproMouseClicked
        // TODO add your handling code here:
        int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez une vente à supprimer.",
                    "Aucune vente sélectionnée", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idVente = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this,
                "Supprimer cette vente ? Le stock des produits sera augmenté des quantités correspondantes.",
                "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            // Récupère les lignes avant suppression pour ajuster le stock
            List<LigneVente> lignes = ligneVenteDAO.listerParVente(idVente);
            for (LigneVente l : lignes) {
                // Annulation de la vente = retour en stock
                produitDAO.mettreAJourStock(l.getIdProd(), l.getQte());
            }
            venteDAO.supprimerVente(idVente);
            chargerVentes();
            JOptionPane.showMessageDialog(this, "Vente supprimée.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de la vente : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSupprimerApproMouseClicked

    /**
     * Affiche une "facture" formatée pour la vente sélectionnée.
     * Utilise les données déjà présentes dans la table (date, ref) et les lignes de vente.
     */
    private void btnFacMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez une vente pour voir la facture.",
                    "Aucune vente sélectionnée", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idVente = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        String dateStr = tableAppro.getValueAt(row, 1).toString();
        String ref = tableAppro.getValueAt(row, 2).toString();
        try {
            List<LigneVente> lignes = ligneVenteDAO.listerParVente(idVente);
            if (lignes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Aucune ligne pour cette vente.",
                        "Facture", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder sb = new StringBuilder();
            // En-tête société
            sb.append("SOCIETE X\n");
            sb.append("Avenue Y, Ville Z\n");
            sb.append("Tél: 000 000 000\n\n");

            // Informations facture
            sb.append("FACTURE DE VENTE\n");
            sb.append("Numéro: ").append(ref).append("\n");
            sb.append("Date  : ").append(dateStr).append("\n\n");

            // Tableau des lignes
            sb.append(String.format("%-25s %8s %12s %12s%n", "Produit", "Qté", "P.V. (FC)", "Total (FC)"));
            sb.append("---------------------------------------------------------------------\n");

            double totalGeneral = 0.0;
            for (LigneVente l : lignes) {
                Produit p = produitDAO.trouverParId(l.getIdProd());
                String nomProd = (p != null) ? p.getNom() : ("ID " + l.getIdProd());
                int qte = l.getQte();
                double pv = l.getPrixVente();
                double totalLigne = qte * pv;
                totalGeneral += totalLigne;

                sb.append(String.format("%-25s %8d %12.2f %12.2f%n",
                        nomProd, qte, pv, totalLigne));
            }

            sb.append("---------------------------------------------------------------------\n");
            sb.append(String.format("%-47s %12.2f%n", "Total HT (FC):", totalGeneral));
            sb.append(String.format("%-47s %12.2f%n", "Taxe (FC):", 0.0));
            sb.append(String.format("%-47s %12.2f%n", "Montant payé (FC):", totalGeneral));

            JOptionPane.showMessageDialog(this, sb.toString(), "Facture de vente",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement des lignes de la vente : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseClicked
        // TODO add your handling code here:
        int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez une vente pour voir les détails.",
                    "Aucune vente sélectionnée", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idVente = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        try {
            List<LigneVente> lignes = ligneVenteDAO.listerParVente(idVente);
            if (lignes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Aucune ligne pour cette vente.",
                        "Détails", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            StringBuilder sb = new StringBuilder();
            sb.append("Lignes pour vente ID ").append(idVente).append(":\n");
            for (LigneVente l : lignes) {
                Produit p = produitDAO.trouverParId(l.getIdProd());
                String nomProd = (p != null) ? p.getNom() : ("ID " + l.getIdProd());
                sb.append("- ").append(nomProd)
                        .append(" | Qte: ").append(l.getQte())
                        .append(" | Prix vente: ").append(l.getPrixVente())
                        .append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString(), "Détails vente",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement détails de la vente : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailsMouseClicked

    private void btnFac2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFac2MouseClicked
        // TODO add your handling code here:
         int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez une vente pour voir la facture.",
                    "Aucune vente sélectionnée", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idVente = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        String dateStr = tableAppro.getValueAt(row, 1).toString();
        String ref = tableAppro.getValueAt(row, 2).toString();
        try {
            List<LigneVente> lignes = ligneVenteDAO.listerParVente(idVente);
            if (lignes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Aucune ligne pour cette vente.",
                        "Facture", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder sb = new StringBuilder();
            // En-tête société
            sb.append("SOCIETE X\n");
            sb.append("Avenue Y, Ville Z\n");
            sb.append("Tél: 000 000 000\n\n");

            // Informations facture
            sb.append("FACTURE DE VENTE\n");
            sb.append("Numéro: ").append(ref).append("\n");
            sb.append("Date  : ").append(dateStr).append("\n\n");

            // Tableau des lignes
            sb.append(String.format("%-25s %8s %12s %12s%n", "Produit", "Qté", "P.V. (FC)", "Total (FC)"));
            sb.append("---------------------------------------------------------------------\n");

            double totalGeneral = 0.0;
            for (LigneVente l : lignes) {
                Produit p = produitDAO.trouverParId(l.getIdProd());
                String nomProd = (p != null) ? p.getNom() : ("ID " + l.getIdProd());
                int qte = l.getQte();
                double pv = l.getPrixVente();
                double totalLigne = qte * pv;
                totalGeneral += totalLigne;

                sb.append(String.format("%-25s %8d %12.2f %12.2f%n",
                        nomProd, qte, pv, totalLigne));
            }

            sb.append("---------------------------------------------------------------------\n");
            sb.append(String.format("%-47s %12.2f%n", "Total HT (FC):", totalGeneral));
            sb.append(String.format("%-47s %12.2f%n", "Taxe (FC):", 0.0));
            sb.append(String.format("%-47s %12.2f%n", "Montant payé (FC):", totalGeneral));

            JOptionPane.showMessageDialog(this, sb.toString(), "Facture de vente",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement des lignes de la vente : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnFac2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.tableApprotName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriqueVenteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnFac2;
    private javax.swing.JButton btnRafraichir;
    private javax.swing.JButton btnSupprimerAppro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAppro;
    // End of variables declaration//GEN-END:variables
}
