/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionpharmavente;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEM'S KABE FILM
 */
public class HistoriqueApproFramee extends javax.swing.JFrame {

    /**
     * Creates new form HistoriqueApproFramee
     */
    private final ApproDAO approDAO = new ApproDAO();
    private final LigneApproDAO ligneApproDAO = new LigneApproDAO();
    private final ProduitDAO produitDAO = new ProduitDAO();
    public HistoriqueApproFramee() {
        initComponents();
        setLocationRelativeTo(null);
        chargerApprovisionnements();
    }

    private void chargerApprovisionnements() {
        try {
            List<Appro> list = approDAO.listerTous();
            DefaultTableModel model = (DefaultTableModel) tableAppro.getModel();
            model.setRowCount(0);
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
            for (Appro a : list) {
                Date d = a.getDateAppro();
                model.addRow(new Object[]{
                    a.getId(),
                    sdf.format(d),
                    a.getRef()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement approvisionnements : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppro = new javax.swing.JTable();
        btnRafraichir = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnSupprimerAppro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historique des approvisionnements");

        tableAppro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE APPRO", "REFERENCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAppro);

        btnRafraichir.setText("Rafraîchir");
        btnRafraichir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRafraichirMouseClicked(evt);
            }
        });

        btnDetails.setText("Détails");
        btnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailsMouseClicked(evt);
            }
        });

        btnSupprimerAppro.setText("Supprimer");
        btnSupprimerAppro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerApproMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnRafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSupprimerAppro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerAppro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRafraichirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRafraichirMouseClicked
        // TODO add your handling code here:
        chargerApprovisionnements();
    }//GEN-LAST:event_btnRafraichirMouseClicked

    private void btnSupprimerApproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerApproMouseClicked
        // TODO add your handling code here:
        int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un approvisionnement à supprimer.",
                    "Aucun approvisionnement sélectionné", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idAppro = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this,
                "Supprimer cet approvisionnement ? Le stock des produits sera diminué des quantités correspondantes.",
                "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            // Récupère les lignes avant suppression pour ajuster le stock
            List<LigneAppro> lignes = ligneApproDAO.listerParAppro(idAppro);
            for (LigneAppro l : lignes) {
                produitDAO.mettreAJourStock(l.getIdProd(), -l.getQte());
            }
            approDAO.supprimerAppro(idAppro);
            chargerApprovisionnements();
            JOptionPane.showMessageDialog(this, "Approvisionnement supprimé.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de l'approvisionnement : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSupprimerApproMouseClicked

    private void btnDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseClicked
        // TODO add your handling code here:
        int row = tableAppro.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un approvisionnement pour voir les détails.",
                    "Aucun approvisionnement sélectionné", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idAppro = Integer.parseInt(tableAppro.getValueAt(row, 0).toString());
        try {
            List<LigneAppro> lignes = ligneApproDAO.listerParAppro(idAppro);
            if (lignes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Aucune ligne pour cet approvisionnement.",
                        "Détails", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            StringBuilder sb = new StringBuilder();
            sb.append("Lignes pour appro ID ").append(idAppro).append(":\n");
            for (LigneAppro l : lignes) {
                Produit p = produitDAO.trouverParId(l.getIdProd());
                String nomProd = (p != null) ? p.getNom() : ("ID " + l.getIdProd());
                sb.append("- ").append(nomProd)
                        .append(" | Qte: ").append(l.getQte())
                        .append(" | Prix achat: ").append(l.getPrixAchat())
                        .append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString(), "Détails approvisionnement",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement détails : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.tableApprotName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriqueApproFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriqueApproFramee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnRafraichir;
    private javax.swing.JButton btnSupprimerAppro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAppro;
    // End of variables declaration//GEN-END:variables
}
