package gestionpharmavente;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JEM'S KABE FILM
 */
public class VenteFrame extends javax.swing.JFrame {

    /**
     * Gestion des ventes (similaire à l'appro mais en sortie de stock).
     */
    private final ProduitDAO produitDAO = new ProduitDAO();
    private final VenteDAO venteDAO = new VenteDAO();
    private final LigneVenteDAO ligneVenteDAO = new LigneVenteDAO();
    private List<Produit> produitsCombo = new ArrayList<>();
    public VenteFrame() {
        initComponents();
        setLocationRelativeTo(null);
        chargerProduitsDansCombo();
        txtDate.setText(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date()));
        txtRef.setText(generateRandomRef());
        
    }
    private String generateRandomRef() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder(8);
        java.util.Random random = new java.util.Random();
        for (int i = 0; i < 8; i++) {
            sb.append(chars.charAt(random.nextInt(chars.length())));
        }
        return sb.toString();
    }
     private void chargerProduitsDansCombo() {
        try {
            produitsCombo = produitDAO.listerTous();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Produit p : produitsCombo) {
                model.addElement(p.getNom());
            }
            comboProduits.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur chargement produits : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtRef = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboProduits = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQte = new javax.swing.JTextField();
        btnAjouterLigne = new javax.swing.JButton();
        btnSupprimerLigne = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLignes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vente");
        setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Date:");

        txtDate.setEditable(false);

        txtRef.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Référence:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Produit:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Qté:");

        btnAjouterLigne.setText("Ajouter une ligne");
        btnAjouterLigne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterLigneMouseClicked(evt);
            }
        });

        btnSupprimerLigne.setText("Supprimer une ligne");
        btnSupprimerLigne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerLigneMouseClicked(evt);
            }
        });

        btnValider.setText("Enregistrer la vente");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnulerMouseClicked(evt);
            }
        });

        tableLignes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUIT", "NOM PRODUIT", "QTE", "PRIX DE VENTE(FC)", "TOTAL (FC)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableLignes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboProduits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQte, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285)
                        .addComponent(btnAjouterLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnSupprimerLigne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnValider)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAjouterLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtQte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimerLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterLigneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterLigneMouseClicked
        int idx = comboProduits.getSelectedIndex();
        if (idx < 0) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un produit.",
                    "Produit manquant", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String qteTxt = txtQte.getText().trim();
        if (qteTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir la quantité.",
                    "Champs manquants", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int qte = Integer.parseInt(qteTxt);
            if (qte <= 0) {
                JOptionPane.showMessageDialog(this, "La quantité doit être strictement positive.",
                        "Quantité invalide", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Produit p = produitsCombo.get(idx);
            double prixVente = p.getPrixVente();
            double total = qte * prixVente;

            DefaultTableModel model = (DefaultTableModel) tableLignes.getModel();
            model.addRow(new Object[]{
                p.getId(),
                p.getNom(),
                qte,
                prixVente,
                total
            });
            txtQte.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vérifiez la valeur numérique de la quantité.",
                    "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAjouterLigneMouseClicked

    private void btnSupprimerLigneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerLigneMouseClicked
        // TODO add your handling code here:
        int row = tableLignes.getSelectedRow();
        if (row >= 0) {
            ((DefaultTableModel) tableLignes.getModel()).removeRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Sélectionnez une ligne à supprimer.",
                    "Aucune ligne sélectionnée", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSupprimerLigneMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableLignes.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Ajoutez au moins une ligne de vente.",
                    "Vente vide", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int idVente = venteDAO.ajouter(new Vente(new Date(), txtRef.getText().trim()));
            if (idVente <= 0) {
                JOptionPane.showMessageDialog(this, "Impossible de créer la vente.",
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            for (int i = 0; i < model.getRowCount(); i++) {
                int idProd = Integer.parseInt(model.getValueAt(i, 0).toString());
                int qte    = Integer.parseInt(model.getValueAt(i, 2).toString());
                double prix = Double.parseDouble(model.getValueAt(i, 3).toString());

                LigneVente l = new LigneVente(idVente, idProd, qte, prix);
                ligneVenteDAO.ajouter(l);
                // Vente = sortie de stock
                produitDAO.mettreAJourStock(idProd, -qte);
            }
            JOptionPane.showMessageDialog(this, "Vente enregistrée avec succès.");
            model.setRowCount(0);
            txtRef.setText(generateRandomRef());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement de la vente : " + ex.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnValiderMouseClicked

    private void btnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnulerMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAnnulerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterLigne;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnSupprimerLigne;
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox<String> comboProduits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableLignes;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtQte;
    private javax.swing.JTextField txtRef;
    // End of variables declaration//GEN-END:variables
}
